import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';
import React, { useMemo } from 'react';
import classNames from 'classnames';
import { useLink } from '../utils/useLink';
import { CONTAIINER_CLASSES } from '../utils/Css';

const PATHS = {
  '': 'Startseite',
  vision: 'Meine Vision',
  reviews: 'Alle Bewertungen',
};

export function Header({ title }: { title: string }) {
  const favicon = useLink('favicon.ico');
  const curPath = useRouter().asPath.substring(1);
  const displayedMenuLinks = useMemo(() => Object.entries(PATHS).filter(([p]) => p !== curPath), [curPath]);
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon} />
      </Head>
      <header className={CONTAIINER_CLASSES}>
        <div className={classNames('mb-4 grid grid-cols-1 justify-around bg-primary p-4 text-onPrimary sm:grid-cols-3')}>
          <h1 style={{ order: displayedMenuLinks.length / 2 }} className="text-xl">{title}</h1>
          {displayedMenuLinks.map(([url, name], idx) => <Link key={url} style={{ order: idx }} className="black text-center text-lg underline" href={`/${url}`}>{name}</Link>)}
        </div>
        {' '}

      </header>
    </>
  );
}
