import Head from 'next/head';

export function Header({ title }: { title: string }) {
  return (
    <header className="mb-4 bg-primary p-4 text-white">
      <h1>{title}</h1>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </header>
  );
}
